FROM ubuntu@sha256:550b0f99b69b0a1dec737f606ee294546466ff281036d4be6aff09bc1ac006fe

RUN apt update -y
RUN apt-get install -y git
RUN apt-get install -y nano 
RUN apt-get install -y jq 
RUN apt-get install -y fio 
RUN apt-get install -y iotop 
RUN apt-get install -y sysstat 
RUN apt-get install -y bpfcc-tools 
RUN apt-get install -y bpftrace 
RUN apt-get install -y blktrace 
RUN apt-get install -y linux-tools-common
RUN apt-get install -y linux-headers-5.0.0-1018-azure # linux-headers-5.0.0-1020-azure
RUN apt-get install -y linux-tools-5.0.0-1018-azure # linux-tools-5.0.0-1020-azure
RUN apt-get install -y magic-wormhole 
RUN apt-get install -y build-essential
RUN git clone https://github.com/brendangregg/FlameGraph.git /flamegraph