name: build images

on:
    push:
        branches:
            - master
    schedule:
        - cron: "0 4 * * *"

env:
    DOCKER_USER: ${{ secrets.DOCKER_USER }}
    DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:
    bpftrace:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                distro: [16.04, 18.04, 19.04]
        steps:
            - uses: actions/checkout@master
            - name: Set up Docker Buildx
              id: buildx
              uses: crazy-max/ghaction-docker-buildx@v1
              with:
                  version: latest
            - name: Available platforms
              run: echo ${{ steps.buildx.outputs.platforms }}
            - name: Cache node modules
              uses: actions/cache@v1
              with:
                path: ${GITHUB_WORKSPACE}/.docker/cache
                key: ${{ matrix.distro }}-docker-build
            - name: Run Buildx
              run: |
                set -eux
                docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
                TAG=$(date -Ihours | tr :+ -)
                echo "TAG: ${TAG}"
                docker buildx build --output=type=local,dest=${GITHUB_WORKSPACE}/.docker/cache --cache-from=${GITHUB_WORKSPACE}/.docker/cache --cache-to=${GITHUB_WORKSPACE}/.docker/cache --build-arg UBUNTU_TAG=${{ matrix.distro }} -f ./images/ubuntu/Dockerfile -t ${DOCKER_USER}/bpf${{ matrix.distro }}:${TAG} .
                ls ${GITHUB_WORKSPACE}/.docker/cache
                docker push ${DOCKER_USER}/bpf${{ matrix.distro }}:${TAG} 
