name: build images

on:
    push:
        branches:
            - master
    schedule:
        - cron: "0 4 * * *"

env:
    DOCKER_USER: ${{ secrets.DOCKER_USER }}
    DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:
    bpftrace:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                distro: [16.04, 18.04]
        steps:
            - uses: actions/checkout@master
            - name: Set up Docker Buildx
              id: buildx
              uses: crazy-max/ghaction-docker-buildx@v1
              with:
                  version: latest
            - name: Available platforms
              run: echo ${{ steps.buildx.outputs.platforms }}
            - name: Run Buildx
              env:
                DISTRO: xenial
                DISTRO_TAG: 16.04
              run: |
                set -eux
                docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
                TAG=$(date -Ihours | tr :+ -)
                echo "TAG: ${TAG}"
                docker buildx build --push --build-arg distro=${DISTRO},distro_tag=${DISTRO_TAG} -f ./images/ubuntu/Dockerfile -t ${DOCKER_USER}/bpf${DISTRO_TAG}:${TAG} .
                docker push ${DOCKER_USER}/bpf${DISTRO_TAG}:${TAG}